test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,17 +6,17 @@ on:
   pull_request:
 
 jobs:
-  # Build job
-  build:
+  check_files:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Setup Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: '3.3' # Not needed with a .ruby-version file
-          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
-          cache-version: 0 # Increment this number if you need to re-download cached gems
-      - name: Build with Jekyll
-        run: bundle exec jekyll build
+      - name: Check for required files
+        run: |
+          for file in index.html README.md _sidebar.md about.md conferences.md resources.md; do
+            if [ ! -f "$file" ]; then
+              echo "Error: $file is missing"
+              exit 1
+            fi
+          done
+          echo "All required files are present"
